### ISSUE TITLE
Node can not reboot

### ISSUE THREAD

**Issue by caicairay** [kftsehk/phy-clusters#18]
cu11 and cu25 were down. Error messages show as below during reboot.

![p90108-140830](https://user-images.githubusercontent.com/33741641/50812974-c5991980-134f-11e9-9cb6-515918d596ce.jpg)

I am not sure if they are relevant, but the red light of one of hard disks is on.

![p90108-141023](https://user-images.githubusercontent.com/33741641/50813044-0133e380-1350-11e9-845b-d2820a8afba5.jpg)

Btw, the red light of cu40 is on as well.

![p90108-141007](https://user-images.githubusercontent.com/33741641/50813109-43f5bb80-1350-11e9-82ba-216939d9493d.jpg)

**Comment by kftsehk** [comment]
Likely the disk failed too like #15 , and it seem disk failure rate is high recently, possibly any reason related to the environment?

**Comment by kftsehk** [comment]
The second image, as I remember, is the hot spare of the raid storage, the red light seems there from the begining

**Comment by caicairay** [comment]
Both cu11 and cu25 have the same issue. :confused:

**Comment by kftsehk** [comment]
Disk is purchased, can find a time for installing.
