### ISSUE TITLE
Unable to establish SSL connection

### ISSUE THREAD

**Issue by kayejlli** [kftsehk/phy-clusters#20]
I was trying to upgrade my scipy package, but got the following errors:

`pip2.7 install --upgrade scipy`

output: 
`Could not fetch URL https://pypi.python.org/simple/scipy/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
Requirement already up-to-date: scipy in ./local/lib/python2.7/site-packages
Could not fetch URL https://pypi.python.org/simple/numpy/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
Requirement already up-to-date: numpy>=1.8.2 in ./local/lib/python2.7/site-packages (from scipy)`

It seems to be issue with the pip version, but I was not able to update the pip either by:

`pip2.7 install --upgrade pip`

which outputs: 
`Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
Requirement already up-to-date: pip in ./local/lib/python2.7/site-packages`

or 

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

which outputs:
` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) SSL connect error`

**Comment by kftsehk** [comment]
Since this OS is out of support, I recommend you to use a python environment offered by anaconda, which should be free of certificate problems.
