### ISSUE TITLE
unable to connect to cluster1

### ISSUE THREAD

**Issue by kayejlli** [kftsehk/phy-clusters#24]
ssh_exchange_identification: read: Connection reset by peer

**Comment by kftsehk** [comment]
After #23, during rollback the head node crashed. Would look into it tomorrow.

**Comment by kftsehk** [comment]
The head node freezed, after reboot inspected log with no interesting findings, also #23 does not reproduce freeze.

It is known that some operations had some probability of causing freeze, so I might suggest it has similar (unknown) root cause.

**Comment by kftsehk** [comment]
Related to #28
