### ISSUE TITLE
cannot submit jobs on cluster1

### ISSUE THREAD

**Issue by terryys** [kftsehk/phy-clusters#25]
On cluster1, qsub returns the following error:

socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd

**Comment by kftsehk** [comment]
I have tested job submit, there is no error as of now from my account. Is the problem still persist?

**Comment by ypwangOrz** [comment]
It's OK, thanks a lot.

**Comment by terryys** [comment]
> 
> 
> I have tested job submit, there is no error as of now from my account. Is the problem still persist?

There is no problem now. Thank you.
