### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by terryys** [kftsehk/phy-clusters#30]
On cluster1, if I try to wget or git clone from an URL, I get the following errors:

syeung@cluster:~> git clone https://www.github.com/cmbant/camb
Cloning into 'camb'...
fatal: unable to access 'https://www.github.com/cmbant/camb/': SSL connect error

syeung@cluster:~> wget https://github.com/cmbant/CAMB/archive/master.zip
--12:20:33--  https://github.com/cmbant/CAMB/archive/master.zip
           => `master.zip'
Resolving github.com... 192.30.253.113
Connecting to github.com|192.30.253.113|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

**Comment by kftsehk** [comment]
Please refer to #20 and https://github.com/kftsehk/phy-clusters/wiki/Anaconda3

If you don't need customised packages, you can simply use a preinstalled environment
```
conda activate
git clone https://www.github.com/cmbant/camb
```
to make this work

**Comment by terryys** [comment]
OK, this works for me too.

**Comment by kftsehk** [comment]
This issue is fixed through updating `ca-certificates`
