### ISSUE TITLE
error when submitting job

### ISSUE THREAD

**Issue by terryys** [kftsehk/phy-clusters#34]
Sometimes when I try to submit a job, I get the following messages and the job is not submitted.

parse_daemon_response error 15008 trqauthd unable to authenticate. User or PID of calling process not found or does not match
parse_daemon_response error 15008 trqauthd unable to authenticate. User or PID of calling process not found or does not match
parse_daemon_response error 15008 trqauthd unable to authenticate. User or PID of calling process not found or does not match
Unable to communicate with cluster(10.1.1.1)
Unable to authorize user.
qsub: cannot connect to server cluster (errno=15008) trqauthd unable to authenticate. User or PID of calling process not found or does not match

**Comment by kftsehk** [comment]
I've look up the log, this error were first seen back in 2015, and intermittedly appears every few days, and would last for about 30-60s.

Here is what would be in the log, suggesting `getpwuid` failed.
```
2019-11-20 10:34:44.2733 UID <uid> returned NULL from getpwuid
2019-11-20 10:34:44.2965 UID <uid> returned NULL from getpwuid
2019-11-20 10:34:44.3199 UID <uid> returned NULL from getpwuid
2019-11-20 10:34:44.3432 UID <uid> returned NULL from getpwuid
2019-11-20 10:34:44.3664 UID <uid> returned NULL from getpwuid
2019-11-20 10:34:44.3866 User <username> at IP:port cluster:15001 login attempt failed --trqauthd unable to authenticate. User or PID of calling process not found or does not match
```

Since your account is from centralized NIS of physics department, I would suspect the problem of failed authentication comes from the NIS server.

**Comment by kftsehk** [comment]
I've confirm with Jason that it is NIS protection on department's side.

As a temporary workaround, you can try to add a few second delay when submitting large number of jobs. For example
```
for i in folder{1..100}
do
    pushd $i
    qsub submit.sh
    sleep 2
    popd
done
```

**Comment by kftsehk** [comment]
Update: We have implement a permanent fix to make all accounts local, so you don't have to use the workaround.

I will close the issue, if you meet the problem again, please re-open.
