### ISSUE TITLE
cannot login cluster1: no route to host

### ISSUE THREAD

**Issue by terryys** [kftsehk/phy-clusters#35]
I tried to login cluster1 from a workstation in the department, but ssh failed to connect with a "no route to host" error.

**Comment by kftsehk** [comment]
There was a problem in cluster1 that resulted in disconnect last night, as of now the cluster is reachable.

**Comment by terryys** [comment]
I can login the server, but when I  try to submit a job, the following error occurs:
socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd

**Comment by kftsehk** [comment]
One partition is full, the queue will resume after the partition is cleaned up.
